### ISSUE TITLE
問題リスト

### ISSUE THREAD

**Issue by anddev68** [moguaiyuki/ponkotsu_store#4]
- [x] /api/login 1: @moguaiyuki #3 
- [x] /api/create 1 -> @satomari #6
- [x] /api/search 1 -> @satomari #10
- [ ] /api/user/all 1 -> #7  
- [x] /api/buy 3 -> @anddev68 #5
  - [x] 割引率のバグ（持ってないクーポンが使える）
  - [x] 別のユーザ（idしか見てない）でも買えるバグ
  - [x] カウントをマイナスにするとお金が増えるバグ
- [ ] /api/forget/resetpass 1 @anddev68 @satomari-san
- [ ] /api/image 3 -> @anddev68 #8
  - [x] ../../../.envがとってこれる(上位ディレクトリが観れてしまう)
  - [ ] .gitignoreがとってこれる(画像ファイル以外が参照可能)
  - [ ] convertコマンドの脆弱性 (未確認)
- [x] /api/goods/[id] 2 -> @anddev68 #9 
  - [x] 他のユーザのパスワードダイジェストが見えてしまう
  - [x] 他のユーザのメールが見えてしまう
- [x] /api/review -> @moguaiyuki  #11
- [ ] その他 2
  - [ ] DEBUGで平文パスワードが見えてる

![image](https://user-images.githubusercontent.com/6037947/79091850-dbcf2a00-7d89-11ea-88f4-daaf37323ac8.png)

**Comment by anddev68** [comment]
# 検査対象
1. [ ] 任意コード実行
2. [ ] 任意OSコマンド実行
3. [x] 一般ユーザーに他のユーザーの個人情報が漏洩(メールアドレス、パスワードハッシュ) 
4. [ ] 管理者に他のユーザーの平文パスワードが漏洩
5. [ ] データベース不正操作
6. [x] 他人のユーザーになりすまして商品が購入できる
7. [x] 残高を不正に操作することができる
8. [x] 不正な購入(残高不足なのに買えるなど)
9. [x] サーバーの任意のファイルが読み出せる(例: .envが読み取れたらダメ) 
10. [x] 他のユーザーのブラウザで任意のjavascriptが実行できる
